# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-08 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_usertoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('img', models.CharField(max_length=32)),
                ('price', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SeniorCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('img', models.CharField(max_length=32)),
                ('price', models.CharField(max_length=32)),
            ],
        ),
    ]
